/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDocsMessageDialog.java
 *
 * Created on 3 Απρ 2014, 8:52:34 μμ
 */
package com.harkon.jdocs.ui.dialog;

import com.harkon.jdocs.main.Application;
import java.awt.Component;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Harris
 */
public class JDocsMessageDialog extends javax.swing.JDialog {

    private static Logger logger = Logger.getLogger(Application.class);

    /** Creates new form JDocsMessageDialog */
    public JDocsMessageDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel1 = new com.harkon.jdocs.ui.TitlePanel();
        transparentPanel1 = new com.harkon.jdocs.swing.TransparentPanel();
        transparentPanel2 = new com.harkon.jdocs.swing.TransparentPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titlePanel1.setName("titlePanel1"); // NOI18N
        getContentPane().add(titlePanel1, java.awt.BorderLayout.PAGE_START);

        transparentPanel1.setName("transparentPanel1"); // NOI18N
        transparentPanel1.setLayout(new java.awt.BorderLayout());

        transparentPanel2.setName("transparentPanel2"); // NOI18N
        transparentPanel2.setLayout(new java.awt.BorderLayout());
        transparentPanel1.add(transparentPanel2, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        transparentPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(transparentPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void showMessage(String message) {
        JOptionPane.showMessageDialog(Application.getJDocsWindow(), message, com.harkon.jdocs.JDocsConstants.MDS_POS, JOptionPane.INFORMATION_MESSAGE, null);
    }

    public static void showError(String message) {
        JOptionPane.showMessageDialog(Application.getJDocsWindow(), message, com.harkon.jdocs.JDocsConstants.MDS_POS, JOptionPane.ERROR_MESSAGE, null);
    }

    public static void showError(Component parent, String message) {
        JOptionPane.showMessageDialog(parent, message, com.harkon.jdocs.JDocsConstants.MDS_POS, JOptionPane.ERROR_MESSAGE, null);
    }

    public static void showError(String message, Throwable x) {
        logger.error(message, x);
        JOptionPane.showMessageDialog(Application.getJDocsWindow(), message, com.harkon.jdocs.JDocsConstants.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null);
    }

    public static void showError(Component parent, String message, Throwable x) {
        logger.error(message, x);
        JOptionPane.showMessageDialog(parent, message, com.harkon.jdocs.JDocsConstants.MDS_POS, JOptionPane.ERROR_MESSAGE, null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.harkon.jdocs.ui.TitlePanel titlePanel1;
    private com.harkon.jdocs.swing.TransparentPanel transparentPanel1;
    private com.harkon.jdocs.swing.TransparentPanel transparentPanel2;
    // End of variables declaration//GEN-END:variables
}
